<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FSD - курьерская служба доставки</title>
    <style>
        a {font-size: 23px}
    </style>
</head>
<body>
<img src="/files/18518b25-f401-476b-ab16-734c31b032be.jpg">
<div style="float: right">
    <a href="/signin" >Вход</a>
    <span> | </span>
    <a href="/signup" >Регистрация</a>
</div>
<p >
    <img style="text-align: center; display: block; width: 100%; height: auto;" src="/files/e37b1c18-974b-4ea0-9b46-5d0b0f2f2fbc.jpg">
</p>


</body>
</html>